### ISSUE TITLE
メンションのアカウント名の表示

### ISSUE THREAD

**Issue by nukaga** [fuwalab/wp-slack-logbot#34]
メンションのアカウント名がID（？）表示になっているようです。アカウント名で表示されるといいなと思いました。
<img width="528" alt="2018-12-05 20 55 12" src="https://user-images.githubusercontent.com/3480985/49512025-1a202380-f8d0-11e8-9251-55809f879402.png">

**Comment by ryotsun** [comment]
リリースしました
