### ISSUE TITLE
表示の順序を変えられないか　時間：発言者：メッセージ

### ISSUE THREAD

**Issue by nukaga** [fuwalab/wp-slack-logbot#35]
今、ログではメッセージの表示が「時間：メッセージ：発言者」となっているのですが、発言者がわかりにくいので、「時間：発言者：メッセージ」に変えられないでしょうか？

**Comment by ryotsun** [comment]
リリースしました。
後日公開するテーマでいい感じのUIになります。
それまではちょっと不格好です；；
